/**
 * BURRA PARIKSHA CMS - Phase 22.6A Provider Configuration Hardening Test Suite
 * 
 * Verifies all 16 required hardening specifications:
 * PA-01 to PA-16
 * 
 * STRICT TEST RULES:
 * - Zero live external AI calls (pure in-memory mock providers).
 * - Zero Google Sheets writes.
 * - Server-controlled provider configuration and resolution.
 * - Credential sanitization (Google, sk-, sk-ant-, gsk_).
 * - Network error classification (ECONNRESET, ETIMEDOUT, etc.).
 */

import { QuestionLanguage, DifficultyLevel } from '../types';
import {
  AIProviderRegistry,
  AIOrchestrator,
  QuestionCandidate,
  AIProviderOptions,
  GenerateCandidateInput,
  GenerationResult,
  DEFAULT_AI_CONFIG,
} from '../lib/ai';
import { MockAIProvider } from '../lib/ai/testing/mock-provider';
import { BlindVerifierRegistry } from '../lib/ai/verifier/blind-verifier.registry';
import { MockBlindVerifierProvider } from '../lib/ai/verifier/mock-blind-verifier';
import {
  sanitizeKeyInMessage,
  classifyAIError,
  AIProviderError,
} from '../lib/ai/error';
import { parseProviderList } from '../lib/ai/config';
import { VerifierArbitrationEngine } from '../lib/ai/verifier/arbitration';
import { CandidateDeterministicAdapter } from '../lib/ai/verifier/deterministic-adapter';

function assert(condition: boolean, message: string): void {
  if (!condition) {
    throw new Error(`[ASSERTION FAILED]: ${message}`);
  }
}

const sampleInput: GenerateCandidateInput = {
  categoryId: 'cat-math',
  topicId: 'topic-algebra',
  subtopicId: 'sub-linear-eq',
  difficulty: DifficultyLevel.MEDIUM,
  language: QuestionLanguage.ENGLISH,
};

async function runTests(): Promise<void> {
  console.log('===============================================================');
  console.log('PHASE 22.6A — PRODUCTION PROVIDER CONFIGURATION HARDENING SUITE');
  console.log('===============================================================\n');

  let passedCount = 0;

  // -------------------------------------------------------------------------
  // PA-01: configured primary resolves correctly
  // -------------------------------------------------------------------------
  console.log('PA-01: Verifying configured primary resolves correctly...');
  {
    const registry = new AIProviderRegistry();
    const mockPrimary = new MockAIProvider('mock-primary-pa01', 'SUCCESS', true, 'primary-model');
    const mockFallback = new MockAIProvider('mock-fallback-pa01', 'SUCCESS', true, 'fallback-model');
    registry.registerProvider(mockPrimary);
    registry.registerProvider(mockFallback);

    const resolution = registry.resolveProviderChain('mock-primary-pa01', ['mock-fallback-pa01']);
    assert(resolution.primaryId === 'mock-primary-pa01', 'Primary ID must match configured primary');
    assert(resolution.availableProviders.length === 2, 'Both registered & configured providers must be available');
    assert(resolution.availableProviders[0].providerId === 'mock-primary-pa01', 'Primary must be first in availableProviders');
    assert(resolution.hasConfiguredProvider === true, 'hasConfiguredProvider must be true');

    const orchestrator = new AIOrchestrator(registry, new BlindVerifierRegistry());
    const res = await orchestrator.generateQuestionCandidate(sampleInput, {
      primaryProviderId: 'mock-primary-pa01',
    });
    assert(res.metadata.providerId === 'mock-primary-pa01', 'Candidate must be generated by configured primary');
    assert(res.metadata.fallbackUsed === false, 'Fallback must not be used when primary succeeds');
    assert(mockPrimary.callCount === 1, 'Primary must be called exactly once');
    assert(mockFallback.callCount === 0, 'Fallback must not be called when primary succeeds');

    passedCount++;
    console.log('  -> PASS: PA-01 configured primary resolves correctly\n');
  }

  // -------------------------------------------------------------------------
  // PA-02: configured primary + fallback resolves in exact order
  // -------------------------------------------------------------------------
  console.log('PA-02: Verifying configured primary + fallback resolves in exact order...');
  {
    const registry = new AIProviderRegistry();
    const pPrimary = new MockAIProvider('p-order', 'TRANSIENT_ERROR', true, 'model-p');
    const fFallback1 = new MockAIProvider('f-order1', 'TRANSIENT_ERROR', true, 'model-f1');
    const fFallback2 = new MockAIProvider('f-order2', 'SUCCESS', true, 'model-f2');

    registry.registerProvider(pPrimary);
    registry.registerProvider(fFallback1);
    registry.registerProvider(fFallback2);

    const resolution = registry.resolveProviderChain('p-order', ['f-order1', 'f-order2']);
    assert(
      JSON.stringify(resolution.resolvedChain) === JSON.stringify(['p-order', 'f-order1', 'f-order2']),
      'Chain resolution must preserve exact primary -> fallback_1 -> fallback_2 order'
    );

    const orchestrator = new AIOrchestrator(registry, new BlindVerifierRegistry());
    const res = await orchestrator.generateQuestionCandidate(sampleInput, {
      primaryProviderId: 'p-order',
      fallbackProviderIds: ['f-order1', 'f-order2'],
    });

    assert(
      JSON.stringify(res.metadata.attemptedProviders) === JSON.stringify(['p-order', 'f-order1', 'f-order2']),
      'Orchestrator must execute providers in exact sequential order'
    );
    assert(res.metadata.providerId === 'f-order2', 'Final candidate must be produced by fallback_2');
    assert(res.metadata.fallbackUsed === true, 'fallbackUsed must be true');
    assert(pPrimary.callCount === 1, 'Primary attempted once');
    assert(fFallback1.callCount === 1, 'Fallback 1 attempted once');
    assert(fFallback2.callCount === 1, 'Fallback 2 attempted once');

    passedCount++;
    console.log('  -> PASS: PA-02 configured primary + fallback resolves in exact order\n');
  }

  // -------------------------------------------------------------------------
  // PA-03: unconfigured primary is skipped safely
  // -------------------------------------------------------------------------
  console.log('PA-03: Verifying unconfigured primary is skipped safely...');
  {
    const registry = new AIProviderRegistry();
    const unconfPrimary = new MockAIProvider('unconf-primary', 'SUCCESS', false, 'unconf-model');
    registry.registerProvider(unconfPrimary);

    assert(registry.isProviderConfigured('unconf-primary') === false, 'Provider must report isConfigured false');
    const status = registry.getProviderStatus('unconf-primary');
    assert(status.isRegistered === true, 'Provider must be registered');
    assert(status.isConfigured === false, 'Provider must not be configured');

    const resolution = registry.resolveProviderChain('unconf-primary');
    assert(resolution.availableProviders.length === 0, 'No available providers in chain');
    assert(resolution.unconfiguredProviders.includes('unconf-primary'), 'Unconfigured primary must be recorded');
    assert(resolution.hasConfiguredProvider === false, 'hasConfiguredProvider must be false');

    const orchestrator = new AIOrchestrator(registry, new BlindVerifierRegistry());
    let threw = false;
    try {
      await orchestrator.generateQuestionCandidate(sampleInput, {
        primaryProviderId: 'unconf-primary',
      });
    } catch (err: any) {
      threw = true;
      assert(err instanceof AIProviderError, 'Must throw structured AIProviderError');
      assert(unconfPrimary.callCount === 0, 'Unconfigured provider must NOT have generateCandidate invoked');
    }
    assert(threw, 'Must safely throw when only unconfigured provider is present');

    passedCount++;
    console.log('  -> PASS: PA-03 unconfigured primary is skipped safely\n');
  }

  // -------------------------------------------------------------------------
  // PA-04: unconfigured primary + configured fallback resolves fallback
  // -------------------------------------------------------------------------
  console.log('PA-04: Verifying unconfigured primary + configured fallback resolves fallback...');
  {
    const registry = new AIProviderRegistry();
    const unconfPrimary = new MockAIProvider('unconf-p4', 'SUCCESS', false, 'unconf-model');
    const confFallback = new MockAIProvider('conf-f4', 'SUCCESS', true, 'conf-model');
    registry.registerProvider(unconfPrimary);
    registry.registerProvider(confFallback);

    const resolution = registry.resolveProviderChain('unconf-p4', ['conf-f4']);
    assert(resolution.unconfiguredProviders.includes('unconf-p4'), 'Primary must be classified as unconfigured');
    assert(resolution.availableProviders.length === 1, 'Only configured fallback should be available');
    assert(resolution.availableProviders[0].providerId === 'conf-f4', 'Available provider must be conf-f4');

    const orchestrator = new AIOrchestrator(registry, new BlindVerifierRegistry());
    const res = await orchestrator.generateQuestionCandidate(sampleInput, {
      primaryProviderId: 'unconf-p4',
      fallbackProviderIds: ['conf-f4'],
    });

    assert(unconfPrimary.callCount === 0, 'Unconfigured primary must be skipped with 0 invocations');
    assert(confFallback.callCount === 1, 'Configured fallback must be invoked');
    assert(res.metadata.providerId === 'conf-f4', 'Candidate must originate from configured fallback');
    assert(res.metadata.fallbackUsed === true, 'fallbackUsed must be true');

    passedCount++;
    console.log('  -> PASS: PA-04 unconfigured primary + configured fallback resolves fallback\n');
  }

  // -------------------------------------------------------------------------
  // PA-05: configured provider missing from registry is handled deterministically
  // -------------------------------------------------------------------------
  console.log('PA-05: Verifying configured provider missing from registry is handled deterministically...');
  {
    const registry = new AIProviderRegistry();
    const confFallback = new MockAIProvider('existing-f5', 'SUCCESS', true, 'f5-model');
    registry.registerProvider(confFallback);

    const statusMissing = registry.getProviderStatus('ghost-provider-xyz');
    assert(statusMissing.isRegistered === false, 'Missing provider isRegistered must be false');
    assert(statusMissing.isConfigured === false, 'Missing provider isConfigured must be false');

    const resolution = registry.resolveProviderChain('ghost-provider-xyz', ['existing-f5']);
    assert(resolution.missingProviders.includes('ghost-provider-xyz'), 'Missing provider must be recorded in missingProviders');
    assert(resolution.availableProviders.length === 1, 'Fallback must be available');
    assert(resolution.availableProviders[0].providerId === 'existing-f5', 'Fallback must resolve');

    const orchestrator = new AIOrchestrator(registry, new BlindVerifierRegistry());
    const res = await orchestrator.generateQuestionCandidate(sampleInput, {
      primaryProviderId: 'ghost-provider-xyz',
      fallbackProviderIds: ['existing-f5'],
    });
    assert(res.metadata.providerId === 'existing-f5', 'Candidate generated by fallback when primary is missing from registry');

    let threwAlone = false;
    try {
      await orchestrator.generateQuestionCandidate(sampleInput, {
        primaryProviderId: 'ghost-provider-xyz',
      });
    } catch (err: any) {
      threwAlone = true;
      assert(err instanceof AIProviderError, 'Must throw structured AIProviderError without crash');
    }
    assert(threwAlone, 'Missing provider alone must deterministically fail without crash');

    passedCount++;
    console.log('  -> PASS: PA-05 configured provider missing from registry is handled deterministically\n');
  }

  // -------------------------------------------------------------------------
  // PA-06: zero configured providers does not crash
  // -------------------------------------------------------------------------
  console.log('PA-06: Verifying zero configured providers does not crash...');
  {
    const emptyRegistry = new AIProviderRegistry();
    const health = emptyRegistry.getHealthStatus();
    assert(health.totalRegistered === 0, 'Zero registered providers');
    assert(health.totalConfigured === 0, 'Zero configured providers');
    assert(health.hasConfiguredProviders === false, 'hasConfiguredProviders must be false');
    assert(Array.isArray(health.providers) && health.providers.length === 0, 'Providers list is empty array');

    const enabled = emptyRegistry.getEnabledProviders();
    assert(Array.isArray(enabled) && enabled.length === 0, 'getEnabledProviders returns empty array');

    const defConfigured = emptyRegistry.getDefaultConfiguredProvider();
    assert(defConfigured === undefined, 'getDefaultConfiguredProvider returns undefined without crashing');

    // Also verify BlindVerifierRegistry
    const emptyVReg = new BlindVerifierRegistry();
    emptyVReg.clear();
    const vHealth = emptyVReg.getHealthStatus();
    assert(vHealth.totalRegistered === 0, 'Verifier total registered is 0');
    assert(vHealth.hasConfiguredProviders === false, 'Verifier hasConfiguredProviders is false');
    assert(emptyVReg.getDefaultConfiguredProvider() === undefined, 'getDefaultConfiguredProvider returns undefined');

    passedCount++;
    console.log('  -> PASS: PA-06 zero configured providers does not crash\n');
  }

  // -------------------------------------------------------------------------
  // PA-07: 429 remains non-retryable
  // -------------------------------------------------------------------------
  console.log('PA-07: Verifying 429 remains non-retryable...');
  {
    const quotaErr1 = { message: 'RESOURCE_EXHAUSTED: quota exceeded', status: 429 };
    const c1 = classifyAIError(quotaErr1);
    assert(c1.classification === 'QUOTA_EXHAUSTED', 'Classifies as QUOTA_EXHAUSTED');
    assert(c1.isRetryable === false, 'Quota exhausted must strictly NOT be retryable');
    assert(c1.statusCode === 429, 'Status code must be 429');

    const rateLimitErr = { message: 'Rate limit exceeded: 429 Too Many Requests', status: 429 };
    const c2 = classifyAIError(rateLimitErr);
    assert(c2.classification === 'RATE_LIMIT', 'Classifies as RATE_LIMIT');
    assert(c2.isRetryable === false, 'Rate limit must strictly NOT be retryable');
    assert(c2.statusCode === 429, 'Status code must be 429');

    const raw429 = { status: 429, message: 'Too Many Requests' };
    const c3 = classifyAIError(raw429);
    assert(c3.isRetryable === false, 'Generic 429 must strictly NOT be retryable');

    passedCount++;
    console.log('  -> PASS: PA-07 429 remains non-retryable\n');
  }

  // -------------------------------------------------------------------------
  // PA-08: ECONNRESET classified transient
  // -------------------------------------------------------------------------
  console.log('PA-08: Verifying ECONNRESET classified transient...');
  {
    const resetErr1 = new Error('read ECONNRESET: connection reset by peer');
    const c1 = classifyAIError(resetErr1);
    assert(c1.classification === 'TRANSIENT_ERROR', 'ECONNRESET classified as TRANSIENT_ERROR');
    assert(c1.isRetryable === true, 'ECONNRESET is retryable');

    const resetErr2 = { code: 'ECONNRESET', message: 'socket connection reset' };
    const c2 = classifyAIError(resetErr2);
    assert(c2.classification === 'TRANSIENT_ERROR', 'code ECONNRESET classified as TRANSIENT_ERROR');
    assert(c2.isRetryable === true, 'code ECONNRESET is retryable');

    const wsarecvErr = new Error('wsarecv: An existing connection was forcibly closed by the remote host.');
    const c3 = classifyAIError(wsarecvErr);
    assert(c3.classification === 'TRANSIENT_ERROR', 'wsarecv connection close classified as TRANSIENT_ERROR');
    assert(c3.isRetryable === true, 'wsarecv connection close is retryable');

    passedCount++;
    console.log('  -> PASS: PA-08 ECONNRESET classified transient\n');
  }

  // -------------------------------------------------------------------------
  // PA-09: ETIMEDOUT classified transient
  // -------------------------------------------------------------------------
  console.log('PA-09: Verifying ETIMEDOUT classified transient...');
  {
    const timedOutErr1 = new Error('connect ETIMEDOUT 142.250.190.46:443');
    const c1 = classifyAIError(timedOutErr1);
    assert(c1.classification === 'TRANSIENT_ERROR', 'ETIMEDOUT classified as TRANSIENT_ERROR');
    assert(c1.isRetryable === true, 'ETIMEDOUT is retryable');

    const socketTimeoutErr = { code: 'ETIMEDOUT', message: 'socket timeout after 30000ms' };
    const c2 = classifyAIError(socketTimeoutErr);
    assert(c2.classification === 'TRANSIENT_ERROR', 'Socket timeout classified as TRANSIENT_ERROR');
    assert(c2.isRetryable === true, 'Socket timeout is retryable');

    passedCount++;
    console.log('  -> PASS: PA-09 ETIMEDOUT classified transient\n');
  }

  // -------------------------------------------------------------------------
  // PA-10: arbitrary unknown error is not automatically transient
  // -------------------------------------------------------------------------
  console.log('PA-10: Verifying arbitrary unknown error is not automatically transient...');
  {
    const err1 = new Error('SyntaxError: Unexpected token < in JSON at position 0');
    const c1 = classifyAIError(err1);
    assert(c1.classification === 'UNKNOWN_ERROR', 'Arbitrary SyntaxError classified as UNKNOWN_ERROR');
    assert(c1.isRetryable === false, 'Arbitrary SyntaxError must NOT be retryable');

    const err2 = 'Some random unhandled calculation assertion failure';
    const c2 = classifyAIError(err2);
    assert(c2.classification === 'UNKNOWN_ERROR', 'Arbitrary string classified as UNKNOWN_ERROR');
    assert(c2.isRetryable === false, 'Arbitrary string must NOT be retryable');

    const err3 = new Error('Database integrity constraint violation');
    const c3 = classifyAIError(err3);
    assert(c3.classification === 'UNKNOWN_ERROR', 'Database error classified as UNKNOWN_ERROR');
    assert(c3.isRetryable === false, 'Database error must NOT be retryable');

    passedCount++;
    console.log('  -> PASS: PA-10 arbitrary unknown error is not automatically transient\n');
  }

  // -------------------------------------------------------------------------
  // PA-11: Google key sanitization
  // -------------------------------------------------------------------------
  console.log('PA-11: Verifying Google key sanitization...');
  {
    const rawKey = 'AIzaSyA12345678901234567890123456789012';
    const rawMsg = `API request to https://generativelanguage.googleapis.com?key=${rawKey} failed with code 400`;
    const sanitized = sanitizeKeyInMessage(rawMsg);

    assert(!sanitized.includes('AIzaSyA'), 'Sanitized message must NOT contain Google key prefix');
    assert(!sanitized.includes(rawKey), 'Sanitized message must NOT contain the Google key');
    assert(sanitized.includes('[REDACTED_KEY]'), 'Sanitized message must contain [REDACTED_KEY]');

    const err = new AIProviderError(`Key ${rawKey} error`, 'gemini', 'gemini-3.1-flash-lite', 'AUTH_ERROR', false);
    assert(!err.message.includes(rawKey), 'AIProviderError message must sanitize Google key');
    assert(err.message.includes('[REDACTED_KEY]'), 'AIProviderError message must contain [REDACTED_KEY]');

    passedCount++;
    console.log('  -> PASS: PA-11 Google key sanitization\n');
  }

  // -------------------------------------------------------------------------
  // PA-12: sk-style key sanitization
  // -------------------------------------------------------------------------
  console.log('PA-12: Verifying sk-style key sanitization...');
  {
    const rawKey = 'sk-1234567890abcdef1234567890abcdef12345678';
    const rawMsg = `OpenAI authorization header Bearer ${rawKey} was rejected`;
    const sanitized = sanitizeKeyInMessage(rawMsg);

    assert(!sanitized.includes('sk-123456'), 'Sanitized message must NOT contain sk- key prefix');
    assert(!sanitized.includes(rawKey), 'Sanitized message must NOT contain sk- key');
    assert(sanitized.includes('Bearer [REDACTED_KEY]'), 'Sanitized message must contain Bearer [REDACTED_KEY]');

    passedCount++;
    console.log('  -> PASS: PA-12 sk-style key sanitization\n');
  }

  // -------------------------------------------------------------------------
  // PA-13: sk-ant-style key sanitization
  // -------------------------------------------------------------------------
  console.log('PA-13: Verifying sk-ant-style key sanitization...');
  {
    const rawKey = 'sk-ant-api03-abcdef1234567890abcdef1234567890';
    const rawMsg = `Anthropic API client initialized with x-api-key: ${rawKey} failed: 401`;
    const sanitized = sanitizeKeyInMessage(rawMsg);

    assert(!sanitized.includes('sk-ant-api03'), 'Sanitized message must NOT contain sk-ant- key prefix');
    assert(!sanitized.includes(rawKey), 'Sanitized message must NOT contain sk-ant- key');
    assert(sanitized.includes('x-api-key: [REDACTED_KEY]'), 'Sanitized message must contain [REDACTED_KEY]');

    passedCount++;
    console.log('  -> PASS: PA-13 sk-ant-style key sanitization\n');
  }

  // -------------------------------------------------------------------------
  // PA-14: gsk_ key sanitization
  // -------------------------------------------------------------------------
  console.log('PA-14: Verifying gsk_ key sanitization...');
  {
    const rawKey = 'gsk_abcdef1234567890abcdef1234567890';
    const rawMsg = `Groq API connection error using credential gsk_abcdef1234567890abcdef1234567890`;
    const sanitized = sanitizeKeyInMessage(rawMsg);

    assert(!sanitized.includes('gsk_abcdef'), 'Sanitized message must NOT contain gsk_ key prefix');
    assert(!sanitized.includes(rawKey), 'Sanitized message must NOT contain gsk_ key');
    assert(sanitized.includes('credential [REDACTED_KEY]'), 'Sanitized message must contain [REDACTED_KEY]');

    passedCount++;
    console.log('  -> PASS: PA-14 gsk_ key sanitization\n');
  }

  // -------------------------------------------------------------------------
  // PA-15: provider resolution remains server-controlled
  // -------------------------------------------------------------------------
  console.log('PA-15: Verifying provider resolution remains server-controlled...');
  {
    // Test safe server-side parsing of env var provider lists
    const parsedClean = parseProviderList('gemini, groq, openai');
    assert(JSON.stringify(parsedClean) === JSON.stringify(['gemini', 'groq', 'openai']), 'Parses valid comma-separated providers');

    const parsedMessy = parseProviderList('  gemini ,  , GROQ  , openai, gemini ');
    assert(JSON.stringify(parsedMessy) === JSON.stringify(['gemini', 'groq', 'openai']), 'Trims, normalizes lowercase, deduplicates, and filters empty items');

    const parsedEmpty = parseProviderList('   ');
    assert(JSON.stringify(parsedEmpty) === JSON.stringify([]), 'Empty/whitespace returns empty array');

    const parsedNull = parseProviderList(undefined);
    assert(JSON.stringify(parsedNull) === JSON.stringify([]), 'Undefined returns empty array');

    // Ensure DEFAULT_AI_CONFIG is server-controlled and non-empty
    assert(typeof DEFAULT_AI_CONFIG.defaultProvider === 'string', 'defaultProvider is defined server-side');
    assert(typeof DEFAULT_AI_CONFIG.defaultVerifierProvider === 'string', 'defaultVerifierProvider is defined server-side');
    assert(Array.isArray(DEFAULT_AI_CONFIG.fallbackProviders), 'fallbackProviders is array server-side');
    assert(Array.isArray(DEFAULT_AI_CONFIG.fallbackVerifierProviders), 'fallbackVerifierProviders is array server-side');

    passedCount++;
    console.log('  -> PASS: PA-15 provider resolution remains server-controlled\n');
  }

  // -------------------------------------------------------------------------
  // PA-16: existing Phase 22.5 behavior remains compatible
  // -------------------------------------------------------------------------
  console.log('PA-16: Verifying existing Phase 22.5 behavior remains compatible...');
  {
    // 1. Deterministic Contradiction short-circuits verifier
    const contradictoryCandidate: QuestionCandidate = {
      content: 'A 300 m long train crosses a 200 m long platform at a speed of 90 km/h. How many seconds does it take?',
      option_a: '20 seconds',
      option_b: '25 seconds',
      option_c: '18 seconds',
      option_d: '15 seconds',
      correct_answer: 'B', // Contradiction: math solver proves 20 seconds is Option A
      explanation: 'Incorrect explanation asserting 25 seconds.',
      difficulty: DifficultyLevel.EASY,
      language: QuestionLanguage.ENGLISH,
    };

    const detResult = CandidateDeterministicAdapter.verifyCandidate(contradictoryCandidate);
    assert(detResult.status === 'CONTRADICTORY', 'Deterministic solver detects contradiction');

    const mockVerifier = new MockBlindVerifierProvider('v-p16', 'mock-verifier-model-v1', {
      solvedOption: 'A',
      confidence: 0.95,
    });
    const arbitration = VerifierArbitrationEngine.arbitrate({
      candidate: contradictoryCandidate,
      deterministicResult: detResult,
      deterministicContradiction: true,
      verifierOutput: null,
    });
    assert(arbitration.verdict === 'INVALID', 'Deterministic contradiction must strictly yield INVALID verdict');
    assert(arbitration.deterministicContradiction === true, 'deterministicContradiction flag set');
    assert(mockVerifier.callCount === 0, 'Verifier must NOT be called on deterministic contradiction');

    // 2. Generator fallback semantics compatibility
    const registry = new AIProviderRegistry();
    const primaryFail = new MockAIProvider('p16-primary', 'TRANSIENT_ERROR', true, 'm-p16');
    const fallbackPass = new MockAIProvider('p16-fallback', 'SUCCESS', true, 'm-fb16');
    registry.registerProvider(primaryFail);
    registry.registerProvider(fallbackPass);

    const orchestrator = new AIOrchestrator(registry, new BlindVerifierRegistry());
    const genResult = await orchestrator.generateQuestionCandidate(sampleInput, {
      primaryProviderId: 'p16-primary',
      fallbackProviderIds: ['p16-fallback'],
    });
    assert(genResult.metadata.providerId === 'p16-fallback', 'Fallback provider succeeded');
    assert(genResult.metadata.fallbackUsed === true, 'fallbackUsed flag set correctly');

    passedCount++;
    console.log('  -> PASS: PA-16 existing Phase 22.5 behavior remains compatible\n');
  }

  console.log('===============================================================');
  console.log(`PHASE 22.6A SUITE COMPLETED: ${passedCount}/16 TESTS PASSED`);
  console.log('===============================================================');
}

runTests().catch((err) => {
  console.error('[FATAL ERROR IN TEST SUITE]:', err);
  process.exit(1);
});
