/**
 * BURRA PARIKSHA CMS - Production Workflow Mock Data
 */

import { PriorityLevel, Video, VideoProductionStatus } from '../../types';

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'BP-VID-101',
    questionId: 'BP-Q-1001',
    title: 'The Viral Escalator Step Trick (CAT/Aptitude)',
    targetDurationSeconds: 58,
    actualDurationSeconds: 56,
    status: VideoProductionStatus.RECORDED,
    priority: PriorityLevel.HIGH,
    queuePosition: 1,
    assignedHost: 'Jithendra (Lead)',
    assignedEditor: 'Video Lab Team',
    driveFolderUrl: 'https://drive.google.com/drive/folders/mock-bp-vid-101',
    rawFootagePath: 'drive://BurraPariksha/Raw/2026/02/BP-VID-101-raw.mp4',
    finalRenderPath: 'drive://BurraPariksha/Renders/BP-VID-101-4k.mp4',
    scheduledRecordingDate: '2026-02-20',
    scheduledPublishDate: '2026-02-26',
    notes: 'Emphasize the relative speed visual overlay in first 3 seconds.',
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-21T17:30:00Z',
  },
  {
    id: 'BP-VID-102',
    questionId: 'BP-Q-1002',
    title: 'Dishonest Merchant False Weight Formula in 30 Seconds',
    targetDurationSeconds: 45,
    status: VideoProductionStatus.SCRIPT_READY,
    priority: PriorityLevel.MEDIUM,
    queuePosition: 2,
    assignedHost: 'Jithendra (Lead)',
    driveFolderUrl: 'https://drive.google.com/drive/folders/mock-bp-vid-102',
    scheduledRecordingDate: '2026-02-25',
    notes: 'Script version 2 approved. Teleprompter cue added.',
    createdAt: '2026-02-08T11:00:00Z',
    updatedAt: '2026-02-22T08:15:00Z',
  },
  {
    id: 'BP-VID-103',
    questionId: 'BP-Q-1003',
    title: 'Clock Reflex Angle Trap: 99% Get This Wrong!',
    targetDurationSeconds: 42,
    actualDurationSeconds: 39,
    status: VideoProductionStatus.EDITING,
    priority: PriorityLevel.URGENT,
    queuePosition: 3,
    assignedHost: 'Jithendra (Lead)',
    assignedEditor: 'Motion FX Pro',
    driveFolderUrl: 'https://drive.google.com/drive/folders/mock-bp-vid-103',
    rawFootagePath: 'drive://BurraPariksha/Raw/BP-VID-103.mov',
    notes: 'Add dynamic zoom-in on the 318° reflex angle graphic.',
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-02-23T14:45:00Z',
  },
  {
    id: 'BP-VID-104',
    questionId: 'BP-Q-1004',
    title: 'Circular Table Seating Arrangement Shortcut',
    targetDurationSeconds: 60,
    actualDurationSeconds: 58,
    status: VideoProductionStatus.READY_TO_UPLOAD,
    priority: PriorityLevel.HIGH,
    queuePosition: 4,
    assignedHost: 'Jithendra (Lead)',
    assignedEditor: 'Motion FX Pro',
    finalRenderPath: 'drive://BurraPariksha/Final/BP-VID-104-master.mp4',
    scheduledPublishDate: '2026-02-24',
    notes: 'Thumbnail generated and pinned comment verified.',
    createdAt: '2026-02-12T14:00:00Z',
    updatedAt: '2026-02-23T18:20:00Z',
  },
  {
    id: 'BP-VID-105',
    questionId: 'BP-Q-1005',
    title: 'Pie Chart Central Angle Mental Math Hack',
    targetDurationSeconds: 40,
    actualDurationSeconds: 40,
    status: VideoProductionStatus.UPLOADED,
    priority: PriorityLevel.MEDIUM,
    youtubeId: 'mock_yt_bp105',
    scheduledPublishDate: '2026-02-18',
    notes: 'Published across YouTube Shorts, Instagram Reels & FB Video.',
    createdAt: '2026-02-14T09:00:00Z',
    updatedAt: '2026-02-18T16:00:00Z',
  },
  {
    id: 'BP-VID-106',
    questionId: 'BP-Q-1006',
    title: 'Pipes & Leakage Trap: The Secret LCM Multiplier',
    targetDurationSeconds: 55,
    status: VideoProductionStatus.QUEUED,
    priority: PriorityLevel.MEDIUM,
    queuePosition: 5,
    assignedHost: 'Jithendra (Lead)',
    notes: 'Waiting for script formulation.',
    createdAt: '2026-02-20T17:00:00Z',
    updatedAt: '2026-02-20T17:00:00Z',
  },
  {
    id: 'BP-VID-107',
    questionId: 'BP-Q-1007',
    title: 'Family Tree Blood Relations Coded Trick',
    targetDurationSeconds: 45,
    status: VideoProductionStatus.SCRIPT_REQUIRED,
    priority: PriorityLevel.LOW,
    queuePosition: 6,
    assignedHost: 'Jithendra (Lead)',
    notes: 'Drafting hook: "My daughter\'s father riddle".',
    createdAt: '2026-02-22T13:30:00Z',
    updatedAt: '2026-02-22T13:30:00Z',
  },
  {
    id: 'BP-VID-108',
    questionId: 'BP-Q-1008',
    title: 'GMAT Critical Reasoning: Weakening Arguments in 60s',
    targetDurationSeconds: 58,
    status: VideoProductionStatus.FINAL_REVIEW,
    priority: PriorityLevel.HIGH,
    assignedHost: 'Jithendra (Lead)',
    assignedEditor: 'Video Lab Team',
    notes: 'Check audio leveling on the final call-to-action.',
    createdAt: '2026-02-21T10:00:00Z',
    updatedAt: '2026-02-24T08:00:00Z',
  },
];
